name: Code Quality (Manual)

on:
  # Disabled on push/PR/schedule to stop failing checks; manual trigger only
  workflow_dispatch:

jobs:
  # Intentionally empty; manual workflow reserved for future ad-hoc runs
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Code Quality checks are disabled and only available via manual run."